In [1]:
import numpy
import pandas


In [2]:
# Predict 2 inputs and and gate output
def AND(x1, x2):
    x = numpy.array([x1, x2]) # create array of inputs
    w = numpy.array([0.5, 0.5]) # create array of weights
    b = -0.7 # create bias
    tmp = numpy.sum(w * x) + b # calculate output
    if tmp <= 0:
        return 0
    else:
        return 1

In [4]:
# take input
x1 = int(input("x1: "))
x2 = int(input("x2: "))
print(AND(x1, x2))

1


In [10]:
# 3 inputs and  Gate output
def AND(x1, x2, x3):
    x = numpy.array([x1, x2, x3]) # create array of inputs
    w = numpy.array([0.5, 0.5, 0.5]) # create array of weights
    b = -0.7 # create bias
    tmp = numpy.sum(w * x) + b # calculate output
    if tmp <= 0:
        return 0
    else:
        return 1

In [11]:
# take input
x1 = int(input("x1: "))
x2 = int(input("x2: "))
x3 = int(input("x3: "))
print(AND(x1, x2, x3))

0


In [17]:
# training data
training_data = matrix([[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]])
print(training_data)


[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


In [18]:
# Sigmoid function
def sigmoid(x):
    return 1 / (1 + numpy.exp(-x))

In [19]:
# Sigmoid derivative
def sigmoid_derivative(x):
    return x * (1 - x)

In [20]:
# Perceptron Learning Algorithm
def train(training_data, epochs):
    # create weights and bias
    w = numpy.random.rand(3)
    b = numpy.random.rand()
    for i in range(epochs):
        for x, y in training_data:
            # forward propagation
            z = numpy.dot(w, x) + b
            pred = sigmoid(z)
            # backward propagation
            error = y - pred
            # update weights and bias
            w += error * sigmoid_derivative(z) * x
            b += error * sigmoid_derivative(z)
    return w, b